FROM tensorflow/tensorflow:2.6.0-gpu-jupyter

RUN pip install --upgrade pip 
RUN pip install jupyterlab==3.2.9
RUN pip install pandas --upgrade
RUN pip install scikit-learn==0.24.1
RUN pip install seaborn==0.11.1
RUN pip install openpyxl
RUN pip install lightgbm==2.2.3
RUN pip install mlflow==1.15.0
RUN pip install tensorboard
RUN pip install git+https://github.com/gaarangoa/ClinicalTransformerV1.git
RUN pip install git+https://github.com/gaarangoa/samecode.git